name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]

    - name: Run unit tests with coverage
      run: |
        make unit_test

    - name: Archive coverage report
      if: success()
      run: |
        mkdir -p artifacts
        cp -r ./htmlcov artifacts/htmlcov
      continue-on-error: true

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: artifacts/htmlcov
